name: Run Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  test:
    name: Run Bun Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Split tests into multiple jobs for parallel execution
        test-group: [1, 2, 3, 4]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests in parallel
        run: |
          case ${{ matrix.test-group }} in
            1)
              # Run S1 Poison Scenario tests
              bun test --bail=false tests/scenarios.test.js -t "S1: Poison Scenario"
              ;;
            2)
              # Run S2 Phantom Scenario tests
              bun test --bail=false tests/scenarios.test.js -t "S2: Phantom Scenario"
              ;;
            3)
              # Run S4 Bomb Duo and S5 Lovers tests
              bun test --bail=false tests/scenarios.test.js -t "S4: Bomb Duo Scenario|S5: Lovers Scenario"
              ;;
            4)
              # Run S6, Movement, and Edge Case tests
              bun test --bail=false tests/scenarios.test.js -t "S6|Movement Constraints|Edge Cases"
              ;;
          esac

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.test-group }}
          path: |
            test-results/
            coverage/
          retention-days: 7

  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: test
    if: always()

    steps:
      - name: Check test results
        run: |
          if [ "${{ needs.test.result }}" = "success" ]; then
            echo "✅ All tests passed!"
          else
            echo "❌ Some tests failed"
            exit 1
          fi
