name: Run Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  test:
    name: Bun Tests (shard ${{ matrix.shard }}/${{ matrix.total }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2]
        total: [2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.0

      - name: Install dependencies
        run: bun install

      - name: Run sharded tests
        run: bun test --shard="${{ matrix.shard }}/${{ matrix.total }}"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.shard }}-of-${{ matrix.total }}
          path: |
            test-results/
            coverage/
          if-no-files-found: ignore
          retention-days: 7
