name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Bun tests (shard ${{ matrix.shard }}/${{ matrix.total }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2]
        total: [2]

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - name: Run sharded tests
        run: bun test --shard "${{ matrix.shard }}/${{ matrix.total }}"
