name: Run Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - shard: "1/2"
            coverage: true
          - shard: "2/2"
            coverage: false
    name: Run Bun Tests (shard ${{ matrix.shard }})
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: |
          CMD="bunx vitest run --reporter=basic --shard=${{ matrix.shard }}"
          if [ "${{ matrix.coverage }}" = "true" ]; then
            CMD="$CMD --coverage"
          fi
          echo "Running: $CMD"
          $CMD

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.shard }}
          path: |
            test-results/
            coverage/
          retention-days: 7
